/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'mcornell' at '5/17/14 11:04 AM' with Gradle 1.12
 *
 * @author mcornell, @date 5/17/14 11:04 AM
 */
class WeatherDataParser {
    WeatherData parseLine(String line) {
        def result = new WeatherData()

        def splitted = line.split()
        result.with {
        	day = convertColumnToInteger(splitted[0])
        	maxTemp = convertColumnToInteger(splitted[1])
        	minTemp = convertColumnToInteger(splitted[2])
        	avgTemp = convertColumnToInteger(splitted[3])
        }
        result
    }

    Integer convertColumnToInteger(String column) {
    	column.collectReplacements { str -> str == '*' ? '' : null } as Integer
    }
}

class WeatherData {
	Integer day
	Integer minTemp
	Integer maxTemp
	Integer avgTemp
}
