/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'mcornell' at '2/26/14 10:55 PM' with Gradle 1.11
 *
 * @author mcornell, @date 2/26/14 10:55 PM
 */

import spock.lang.Specification
import spock.lang.Unroll

class FizzBuzzSpec extends Specification{

	@Unroll
    def "Calculates FizzBuzz for #value"() {
        setup:
        def fizzbuzz = new FizzBuzz()
        expect:
        result == fizzbuzz.calculate(value)
        where:
        value || result
        1     || 1
        2     || 2
        3	  || 'fizz'
        5 	  || 'buzz'
        6     || 'fizz'
        10    || 'buzz'
        11    || 11
        15    || 'fizzbuzz'
        21    || 'fizz'
        30    || 'fizzbuzz'
        99    || 'fizz'
        100   || 'buzz'
    }
}
