/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'mcornell' at '2/26/14 10:55 PM' with Gradle 1.11
 *
 * @author mcornell, @date 2/26/14 10:55 PM
 */
class FizzBuzz {
    def calculate(int num) {
        num == 3 ? 'fizz' : num
    }
}
