/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'mcornell' at '3/3/14 9:13 PM' with Gradle 1.11
 *
 * @author mcornell, @date 3/3/14 9:13 PM
 */
class RomanNumerals {
    def translate(int number) {
        'I'
    }
}
