/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'mcornell' at '5/17/14 11:04 AM' with Gradle 1.12
 *
 * @author mcornell, @date 5/17/14 11:04 AM
 */

import spock.lang.Specification

class FootballDataSpec extends Specification {

	def footballDataParser
    def dataFile

	void setup() {
		footballDataParser = new FootballDataParser()
        dataFile = this.getClass().getResource('/football.dat');
	}

    def "it can parse a line from the data file"() {
        given:
        def dataLine = '    4. Newcastle       38    21   8   9    74  -  52    71'
        when:
        def result = footballDataParser.parseLine(dataLine)
        then:
        result.name == 'Newcastle'
        result.goalsFor == 74
        result.goalsAgainst == 52
    }

    def "it can read all of the team data"() {
        when:
        def result = footballDataParser.readData(dataFile)
        then:
        result.size == 20
        result[0].name == 'Arsenal'
        result[19].name == 'Leicester'
    }

    def "it can determine the team with the largest spread in goals for and against"() {
        when:
        def result = footballDataParser.findLargestSpread(dataFile)
        then:
        result.name == 'Arsenal'
        result.spread == 43
    }
    
}
